apiVersion: v1
kind: Service
metadata:
  name: faask-service
  labels:
    app: flask
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5431
  type: NodePort
