apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mlops-simple-pipeline-
spec:
  entrypoint: pipeline
  arguments:
    parameters:
    - name: bucket
      value: bucket_project-2023-409616

  templates:
  - name: pipeline
    steps:
    - - name: ETL-Process
        template: etl
    - - name: Model-Training
        template: training

#  templates:
  - name: etl
    container:
      image: sayyeddocker123/etl:latest
      env:
      - name: BUCKET
        value: "{{workflow.parameters.bucket}}"
  - name: training
    container:
      image: sayyeddocker123/model_training:latest
      env:
      - name: BUCKET
        value: "{{workflow.parameters.bucket}}"
