apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appname }}
    app.kubernetes.io/instance: {{ .Values.appname }}
  name: {{ .Values.appname }}-srv
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.appname }}
  type: ClusterIP