name: ML Workflows Via Actions
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step One - checkout files in repo
      uses: actions/checkout@v3

    #- name: Install kubectl
      #uses: azure/setup-kubectl@v2.0
      #with:
        #version: 'v1.29.0' # default is latest stable
      #id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.REGION}}


    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{secrets.ECR_REPO_NAME}}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./containers/model_serving/
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: login repo    
      uses: actions/checkout@v3
      with:
        repository: sayyed-123/argo-flask-infra
        ref: 'main'
        token: ${{ secrets.G_TOKEN }}
    - name: setup git config
      run: |
        git config user.email "mudassar.sayyed45@gmail.com"
        git config user.name "sayyed-123"
        sed 's/TAG/${{ github.sha }}/g' demo/dep-demo.yaml > deployment.yaml
        git add .
        git commit -m "Update image for - ${{ github.sha }}"
    - run: echo ${{ github }}
    - run: git push origin main     
    
    #- name: Update kube config
      #run: aws eks update-kubeconfig --name my-cluster